# Generated by Django 4.2.4 on 2023-08-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexNumber', models.CharField(max_length=10)),
                ('courseCode', models.CharField(max_length=15)),
                ('courseName', models.CharField(max_length=100)),
                ('atendanceTime', models.DateTimeField(auto_now=True)),
                ('invigilator', models.CharField(max_length=100)),
                ('isPresent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100)),
                ('courseCode', models.CharField(max_length=15)),
                ('creditHours', models.PositiveIntegerField()),
                ('lecturerID', models.CharField(max_length=200)),
            ],
        ),
    ]
