# Generated by Django 4.2.4 on 2023-08-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invigilator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(max_length=15)),
                ('courseName', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LecturerSemeterCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('className', models.CharField(max_length=200)),
                ('courseCode', models.CharField(max_length=10)),
                ('courseName', models.CharField(max_length=200)),
                ('creditHours', models.IntegerField()),
            ],
        ),
    ]
