# Generated by Django 4.2.4 on 2023-08-23 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecturers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invigilator',
            name='invigilatorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
